permalink: /:categories/:title.html
url: "http://pasindud.github.io/jekyll-masonry/"
full_name: "Andreas Klein"
first_name: "Andreas"
last_name: "Klein"
copyright_year: "2015"
blog_title: "Kungis Book list"
author_img_name_path: "/images/users/user.jpg"
aboutme: "Something about the author here"
linkined_url: ""
exclude: [.hyde.el]